version: "3"

services:
  postgres_1:
    image: postgres
    container_name: bank_1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    restart: always

  postgres_2:
    image: postgres
    container_name: bank_2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bank
    ports:
      - "5433:5432"
    volumes:
      - postgres:/data/postgres
    restart: always

volumes:
  postgres: