version: "3"

services:
  postgres_1:
    image: postgres
    container_name: bank_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    restart: always

volumes:
  postgres: